mmitv_back:
    resource: "@mmitvBackBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /dashboard/profile

fos_user_pass:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /dashboard/profile/
