mmitv_front:
    resource: "@mmitvFrontBundle/Resources/config/routing.yml"
    prefix:   /

mmitv_back:
    resource: "@mmitvBackBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
