mmitv\BackBundle\Entity\Playlists:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        playlistNom:
            type: string
            length: '50'
            column: playlist_nom
        playlistDebut:
            type: decimal
            column: playlist_debut
        playlistFin:
            type: decimal
            column: playlist_fin
        playlistHeureDiff:
            type: time
            column: playlist_heure_diff
        playlistJourDiff:
            type: date
            column: playlist_jour_diff
    lifecycleCallbacks: {  }
