mmitv_home:
    path :    /
    defaults : {_controller: mmitvBackBundle:Default:index}

mmitv_dashboard:
    path :    /dashboard
    defaults : {_controller: mmitvBackBundle:Dashboard:dashboard}

mmitv_ifaceTV:
    path :    /tv
    defaults : {_controller: mmitvBackBundle:TV:index}

mmitv_gestion_utilisateur:
    path :    /dashboard/gestion-utilisateur
    defaults : {_controller: mmitvBackBundle:GestionUtilisateur:index}

mmitv_gestion_utilisateur_promouvoir:
    path :    /dashboard/gestion-utilisateur/promouvoir-{id}
    defaults : {_controller: mmitvBackBundle:GestionUtilisateur:promote}

mmitv_gestion_utilisateur_downgrade:
    path :    /dashboard/gestion-utilisateur/downgrade-{id}
    defaults : {_controller: mmitvBackBundle:GestionUtilisateur:downgrade}

mmitv_gestion_utilisateur_supprimer:
    path :    /dashboard/gestion-utilisateur/supprimer-{id}
    defaults : {_controller: mmitvBackBundle:GestionUtilisateur:supprimer}

mmitv_addvideo:
    path :    /dashboard/video/ajouter_video
    defaults : {_controller: mmitvBackBundle:AddVideo:add}

mmitv_createplaylist:
    path :    /dashboard/playlist/creer_playlist
    defaults : {_controller: mmitvBackBundle:CreatePlaylist:create}

mmitv_editplaylist:
    path :    /dashboard/playlist/editer_playlist
    defaults : {_controller: mmitvBackBundle:EditPlaylist:edit}

mmitv_grille:
    path :    /dashboard/grille
    defaults : {_controller: mmitvBackBundle:Grille:grille}

mmitv_updatevideo:
    path : /dashboard/updatevideo/{id}
    defaults : { _controller: mmitvBackBundle:EditVideo:update}
    requirements:
        id : \d*

mmitv_deletevideo:
    path : /dashboard/deletevideo/{id}
    defaults : { _controller: mmitvBackBundle:EditVideo:delete}
    requirements:
        id : \d*


mmitv_deleteplaylist:
    path: /dashboard/deleteplaylist/{id}
    defaults : { _controller: mmitvBackBundle:EditPlaylist:removePlaylist}
    requirements:
        id : \d*

mmitv_updateplaylist:
    path: /dashboard/updateplaylist/{id}
    defaults : { _controller: mmitvBackBundle:EditPlaylist:updatePlaylist}
    requirements:
        id : \d*

mmitv_removevideoplaylist:
    path: /dashboard/updateplaylist/remove/{playlist_id}/{video_id}
    defaults: { _controller: mmitvBackBundle:EditPlaylist:removeVideoPlaylist}
    requirements:
        playlist_id: \d*
        video_id : \d*

mmitv_addvideoplaylist:
    path: /dashboard/updateplaylist/add/{playlist_id}/{video_id}
    defaults: { _controller: mmitvBackBundle:EditPlaylist:addVideoPlaylist}
    requirements:
        playlist_id: \d*
        video_id : \d*

mmitv_info:
    path:   /dashboard/infos
    defaults : {_controller: mmitvBackBundle:Info:index}

mmitv_info_add:
    path:   /dashboard/infos/ajouter
    defaults : {_controller: mmitvBackBundle:Info:add}

mmitv_info_delete:
    path:   /dashboard/infos/supprimer/{id}
    defaults: {_controller: mmitvBackBundle:Info:delete}

mmitv_info_edit:
    path:   /dashboard/infos/modifier/{id}
    defaults: {_controller: mmitvBackBundle:Info:edit}


mmitv_indexprogramme:
    path: /dashboard/programmes
    defaults: { _controller: mmitvBackBundle:GestionProgramme:index}

mmitv_removeprogramme:
    path: /dashboard/programmes/remove/{id}
    defaults: { _controller: mmitvBackBundle:GestionProgramme:removeProgramme}
    requirements:
        id: \d*

mmitv_updateprogramme:
    path: /dashboard/programmes/update/{id}
    defaults: { _controller: mmitvBackBundle:GestionProgramme:updateProgramme}
    requirements:
        id: \d*

mmitv_removeplaylistprogramme:
    path: /dashboard/programmes/update/remove/{programme_id}/{playlist_id}
    defaults: { _controller: mmitvBackBundle:GestionProgramme:removePlaylistProgramme}
    requirements:
        programme_id: \d*
        playlist_id: \d*

mmitv_addplaylistprogramme:
    path: /dashboard/programmes:update/add/{programme_id}/{playlist_id}
    defaults: { _controller: mmitvBackBundle:GestionProgramme:addPlaylistProgramme}
    requirements:
        programme_id: \d*
        playlist_id: \d*

mmitv_ifaceTV_info:
    path:   /tv/json
    defaults: { _controller: mmitvBackBundle:TV:infosJson,_format:json}

mmitv_emploidutemps:
    path:   /dashboard/emploidutemps
    defaults: { _controller: mmitvBackBundle:EmploiDuTemps:getEDT}