mmitv_home:
    path :    /
    defaults : {_controller: mmitvBackBundle:Default:index}

mmitv_dashboard:
    path :    /dashboard
    defaults : {_controller: mmitvBackBundle:Dashboard:dashboard}

mmitv_menu:
    path :    /dashboard
    defaults : {_conroller: mmitvBackBundle:Menu:menu}

mmitv_ifaceTV:
    path :    /tv
    defaults : {_controller: mmitvBackBundle:TV:index}

mmitv_gestion_utilisateur:
    path :    /dashboard/gestion-utilisateur
    defaults : {_controller: mmitvBackBundle:GestionUtilisateur:afficheUser}
