mmitv_home:
    path :    /
    defaults : {_controller: mmitvBackBundle:Default:index}

mmitv_dashboard:
    path :    /dashboard
    defaults : {_controller: mmitvBackBundle:Dashboard:dashboard}

mmitv_menu:
    path :    /dashboard
    defaults : {_conroller: mmitvBackBundle:Menu:menu}

mmitv_ifaceTV:
    path :    /tv
    defaults : {_controller: mmitvBackBundle:TV:index}

mmitv_gestion_utilisateur:
    path :    /dashboard/gestion-utilisateur
    defaults : {_controller: mmitvBackBundle:GestionUtilisateur:afficheUser}

mmitv_header:
    path :    /dashboard
    defaults : {_controller: mmitvBackBundle:Header:header}

mmitv_addvideo:
    path :    /dashboard/add_video
    defaults : {_controller: mmitvBackBundle:AddVideo:add}

mmitv_createplaylist:
    path :    /dashoboard/create_playlist
    defaults : {_controller: mmitvBackBundle:CreatePlaylist:create}

mmitv_editplaylist:
    path :    /dashboard/edit_playlist
    defaults : {_controller: mmitvBackBundle:EditPlaylist:edit}

mmitv_grille:
    path :    /dashboard//grille
    defaults : {_controller: mmitvBackBundle:Grille:grille}

mmitv_updatevideo:
    path : /dashboard/updatevideo/{id}
    defaults : { _controller: mmitvBackBundle:EditVideo:update}
    requirements:
        id : \d*

mmitv_deletevideo:
    path : /dashboard/deletevideo/{id}
    defaults : { _controller: mmitvBackBundle:EditVideo:delete}
    requirements:
        id : \d*
